"""Smoke tests for src/advocate/models.py (auto-generated by pact adopt)."""

import pytest

def test_import_advocate_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("advocate.models")
    assert mod is not None
