"""Smoke tests for src/advocate/provider.py (auto-generated by pact adopt)."""

import pytest

def test_import_advocate_provider():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("advocate.provider")
    assert mod is not None

def test_estimate_cost_is_callable():
    """Function estimate_cost exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.provider")
    fn = getattr(mod, "estimate_cost", None)
    assert fn is not None, "'estimate_cost' not found in advocate.provider"
    assert callable(fn)

def test_create_provider_is_callable():
    """Function create_provider exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.provider")
    fn = getattr(mod, "create_provider", None)
    assert fn is not None, "'create_provider' not found in advocate.provider"
    assert callable(fn)

def test_transmogrify_is_callable():
    """Function transmogrify exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.provider")
    fn = getattr(mod, "transmogrify", None)
    assert fn is not None, "'transmogrify' not found in advocate.provider"
    assert callable(fn)
