"""Smoke tests for src/advocate/engine.py (auto-generated by pact adopt)."""

import pytest

def test_import_advocate_engine():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("advocate.engine")
    assert mod is not None

def test_review_is_callable():
    """Function review exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.engine")
    fn = getattr(mod, "review", None)
    assert fn is not None, "'review' not found in advocate.engine"
    assert callable(fn)

def test_load_input_is_callable():
    """Function load_input exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.engine")
    fn = getattr(mod, "load_input", None)
    assert fn is not None, "'load_input' not found in advocate.engine"
    assert callable(fn)
