"""Smoke tests for src/advocate/report.py (auto-generated by pact adopt)."""

import pytest

def test_import_advocate_report():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("advocate.report")
    assert mod is not None

def test_print_review_is_callable():
    """Function print_review exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.report")
    fn = getattr(mod, "print_review", None)
    assert fn is not None, "'print_review' not found in advocate.report"
    assert callable(fn)

def test_write_json_is_callable():
    """Function write_json exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.report")
    fn = getattr(mod, "write_json", None)
    assert fn is not None, "'write_json' not found in advocate.report"
    assert callable(fn)

def test_write_html_is_callable():
    """Function write_html exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.report")
    fn = getattr(mod, "write_html", None)
    assert fn is not None, "'write_html' not found in advocate.report"
    assert callable(fn)
