"""Smoke tests for src/advocate/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_advocate_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("advocate.cli")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in advocate.cli"
    assert callable(fn)

def test_review_is_callable():
    """Function review exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.cli")
    fn = getattr(mod, "review", None)
    assert fn is not None, "'review' not found in advocate.cli"
    assert callable(fn)

def test_personas_is_callable():
    """Function personas exists and is callable."""
    import importlib
    mod = importlib.import_module("advocate.cli")
    fn = getattr(mod, "personas", None)
    assert fn is not None, "'personas' not found in advocate.cli"
    assert callable(fn)
